version: '3.7'

services:
  application:
    container_name: invoices-application
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - invoices-network
    depends_on:
      - mysql
  mysql:
    container_name: invoices-mysql
    image: mysql:5.7
    command: --sql_mode=""
    networks:
      - invoices-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: invoices
    volumes:
      - ./.docker/data/mysql/:/var/lib/mysql
      - ./.docker/logs/mysql/:/var/log/mysql
    ports:
      - "3306:3306"
networks:
  invoices-network: